[package]
name = "tstd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.14"
paste = "1.0.6"
casey = "0.3.3"
quote = "1.0.15"
seq-macro = "0.3.0"